steps:
  # Frontend deployment
  # Build the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mindmate-frontend:$COMMIT_SHA', '-f', './app/frontend/Dockerfile', './app/frontend']
  
  # Push the frontend container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mindmate-frontend:$COMMIT_SHA']
  
  # Deploy frontend container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mindmate-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mindmate-frontend:$COMMIT_SHA'
      - '--region'
      - 'europe-west2'  # London region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

  # Backend deployment
  # Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mindmate-backend:$COMMIT_SHA', '-f', './app/backend/Dockerfile', './app/backend']
  
  # Push the backend container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mindmate-backend:$COMMIT_SHA']
  
  # Deploy backend container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mindmate-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mindmate-backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west2'  # London region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/mindmate-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/mindmate-backend:$COMMIT_SHA'
