steps:
  # Frontend deployment only
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mindmate-frontend:latest', '-f', './app/frontend/Dockerfile', './app/frontend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mindmate-frontend:latest']

images:
  - 'gcr.io/$PROJECT_ID/mindmate-frontend:latest'
